print("Assignment_1")
print("===================================================================")
First_line = ('    '"Twinkle, twinkle, little star,")
Second_line = ('           '"How I wonder what you are!")
Third_line = ('                   '"Up above the world so high,")
Fourth_line = ('                  '"Like a diamond in the sky.")
Fifth_line = ('    '"Twinkle, twinkle, little star,")
Sixth_line = ('            '"How I wonder what you are")
#--------------------------------------------------------------------------
print(First_line)
print(Second_line)
print(Third_line)
print(Fourth_line)
print(Fifth_line)
print(Sixth_line)
print("---------------------------------------------------------------------")
print("Assignment By: Muhammad Imtiaz Hussain")
